'use server';

/**
 * @fileOverview This file defines a Genkit flow to generate a personalized introduction for a user based on their 'about' section and preferences.
 *
 * - generatePersonalizedIntroduction - A function that generates a personalized introduction.
 * - GeneratePersonalizedIntroductionInput - The input type for the generatePersonalizedIntroduction function.
 * - GeneratePersonalizedIntroductionOutput - The return type for the generatePersonalizedIntroduction function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePersonalizedIntroductionInputSchema = z.object({
  about: z
    .string()
    .describe('The user provided description about themselves.'),
  preferences: z
    .string()
    .describe('The user provided preferences for a relationship.'),
});

export type GeneratePersonalizedIntroductionInput = z.infer<
  typeof GeneratePersonalizedIntroductionInputSchema
>;

const GeneratePersonalizedIntroductionOutputSchema = z.object({
  introduction: z
    .string()
    .describe('A personalized introduction generated by the AI.'),
  icebreakerQuestion: z
    .string()
    .describe('An icebreaker question to start a conversation.'),
});

export type GeneratePersonalizedIntroductionOutput = z.infer<
  typeof GeneratePersonalizedIntroductionOutputSchema
>;

export async function generatePersonalizedIntroduction(
  input: GeneratePersonalizedIntroductionInput
): Promise<GeneratePersonalizedIntroductionOutput> {
  return generatePersonalizedIntroductionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePersonalizedIntroductionPrompt',
  input: {schema: GeneratePersonalizedIntroductionInputSchema},
  output: {schema: GeneratePersonalizedIntroductionOutputSchema},
  prompt: `You are an AI assistant designed to create personalized introductions and icebreaker questions for online dating profiles.

  Based on the user's "about" section and relationship preferences, generate a short, engaging introduction and a relevant icebreaker question.

  About: {{{about}}}
  Preferences: {{{preferences}}}

  Introduction:
  Icebreaker Question: `,
});

const generatePersonalizedIntroductionFlow = ai.defineFlow(
  {
    name: 'generatePersonalizedIntroductionFlow',
    inputSchema: GeneratePersonalizedIntroductionInputSchema,
    outputSchema: GeneratePersonalizedIntroductionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
